apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restapi-app.fullname" . }}
  labels:
    app: {{ include "restapi-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "restapi-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "restapi-app.name" . }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8001