apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: my-restapi-project
build:
  local:
    push: false
  artifacts:
    - image: restapi-dev
      context: backend
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        infer: []
    - image: restapi-prod
      context: backend
      docker:
        dockerfile: Dockerfile
        target: production
      sync:
        infer: []
deploy:
  helm:
    releases:
      - name: restapi-app
        chartPath: charts/restapi-app
        valuesFiles:
          - charts/restapi-app/values.yaml  # common valuesFile
        setValues:
          hpa.enabled: true  # common settins

profiles:
  - name: dev
    build:
      artifacts:
        - image: restapi-dev
          context: backend
          docker:
            dockerfile: Dockerfile
            target: development
    deploy:
      helm:
        releases:
          - name: restapi-app-dev
            chartPath: charts/restapi-app
            setValues:
              backend.image: restapi-dev:latest  # Changing settings for each profile
              hpa.enabled: false 
    portForward:
    - resourceType: service
      resourceName: restapi-app-dev-restapi-app
      port: 8000
      localPort: 8000
      namespace: default      

  - name: prod
    build:
      artifacts:
        - image: restapi-prod
          context: backend
          docker:
            dockerfile: Dockerfile
            target: production
    deploy:
      helm:
        releases:
          - name: restapi-app-prod
            chartPath: charts/restapi-app
            setValues:
              backend.image: restapi-prod:latest  # Changing settings for each profile
              hpa.enabled: true  